//  export method // Should not minimize
 export_Editordjeanner_Version1_SourceMnovaJson_IDnone(param) {
	/* param:
	dataObj        : dataObj,
	objDataField   : dataObj.item.objDataField,
	creatorParam   : dataObj.creatorParam,
	targetObjType  : targetObjType,
	object         : dataObj.objSource
	objoutputFields
	*/
	const obj = this.data;
	const objDataField = param.objDataField;
	const objectObj = param.objectObj;
	if (!objectObj) {
		console.error(
			"No objectObj string in param. Error generated by export_Editordjeanner_Version1_SourceMnovaJson_IDnone param : ",
			param
		);
		return {};
	}
	if (objectObj === "NMRspectrumObject") {
		if (objDataField.passedList[0] === "field1") {
			oneSpectrum = buildFromNMRspectrumObject(objDataField, obj);

			const mnovaDataset = {
				$mnova_schema:
					"https://mestrelab.com/json-schemas/mnova/2023-07/01/nmr/dataset",
				spectra: [oneSpectrum],
			};

			return mnovaDataset;
		}
	}

	if (objectObj === "ZZZZZZZZ") {
		var retObj = {};
		var retObj = {};
		if (objDataField.passedList[0] === "field1") {
			retObj.dummy_data = 33;
			return retObj;
		}
		if (objDataField.passedList[0] === "field2") {
			retObj.dummy_data = 44;
			return retObj;
		}
		return retObj;
	}
	console.error("objDataField : ", objectObj);
	console.error(
		`objDataField : ${objectObj} not implemented from export_Editordjeanner_Version1_SourceMnovaJson_IDnone`
	);
	return {};
}
